dist: trusty
sudo: true
before_install:
- sudo apt-get update -qq
- sudo apt-get install texlive-latex-base
before_deploy:
- git fetch --tags
deploy:
  provider: releases
  file: main.tex
  skip_cleanup: true
  on:
    repo: aliceblack/LatexTravis
    tags: true
