sudo: true
dist: trusty
before_install:
- sudo apt-get update -qq
- sudo apt-get install texlive-latex-base
script:
- mkdir build
- pdflatex -output-directory build main.tex
before_deploy:
- git checkout -b master
- git fetch --tags
deploy:
  provider: releases
file: main.tex
  on:
    repo: aliceblack/LatexTravisBoilerplate
    tags: true
    all_branches: true
